general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[shell]
program = "fish"
#args = ["attach", "-c", "main"]

[font]
normal = { family = "HackGen Console NF" }
bold = { family = "HackGen Console NF" }
italic = { family = "HackGen Console NF" }
size = 11

[window]
#padding.x = 14
#padding.y = 14
#decorations = "None"
